spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/book
    username: root
    password: 19970211
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
