spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://www.safewind.cn:3306/book?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Ll123456?
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
server:
  tomcat:
    uri-encoding: UTF-8




borderTime: 2592000000 #3600*1000*24*30
Fee: 50 #罚款50
